---
name: JSON-Tiny
version: 0.1.1
author: 
    - 'Moritz Lenz <moritz@faui2k3.org>'
    - 'Johan Viklund <johan.viklund@gmail.com>'
abstract: 'JSON parser and generator'
license: artistic_2
resources:
    license: http://www.perlfoundation.org/artistic_2_0_notes
distribution_type: module
requires:
    perl: 6.0
provides:
    JSON::Tiny:
        file: lib/JSON/Tiny.pm
        version: 0.1.1
    JSON::Tiny::Grammar:
        file: lib/JSON/Tiny/Grammar.pm
    JSON::Tiny::Actions:
        file: lib/JSON/Tiny/Actions.pm
generated_by: 'Moritz Lenz'
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2

